name: "ECR Cache"
description: "Store container images in a designated ECR repository between jobs."
inputs:
  repository-url:
    description: "The URL of an ECR repository."
    required: true
  image-tag:
    description: "An image tag or list of image tags."
    required: true
  run-number:
    description: "The number of a previous workflow run."
    required: false
runs:
  using: "node16"
  main: "lib/main.mjs"
