name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Bump version
        id: bump_version
        run: |
          npm version patch
          PACKAGE_VERSION=$(cat package.json \
            | grep version \
            | head -1 \
            | awk -F: '{ print $2 }' \
            | sed 's/[",]//g')
          echo "package_version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT

      - name: Commit build output
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Merge build output [skip-ci]
          file_pattern: "lib/**/* package.json"

      - name: Tag version
        run: |
          git tag \
            -a v${{ steps.bump_version.outputs.package_version }} \
            -m "Version ${{ steps.bump_version.outputs.package_version }}"
